issuer: https://dex.pyl.one
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: 0.0.0.0:5556
connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: Iv23lisOtqwHgyNWK0dK
      clientSecret: 88606fba09e560028908d248878e3db84da27c20
      redirectURI: https://dex.pyl.one/callback
staticClients:
  - id: hyvor-relay
    secret: LJRvbNDBp8aDlAqL2uwPRW9XZR1Zi7Km
    name: Hyvor Relay
    redirectURIs:
      - https://relay.pyl.one/api/oidc/callback
