issuer: https://dex.pyl.one
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: 0.0.0.0:5556
connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: Ov23livOHiPmvYPhWFGE
      clientSecret: 2f10530e5a7d0e84aabc46452e8012fa5daaa0c5
      redirectURI: https://dex.pyl.one/callback
staticClients:
  - id: hyvor-relay
    secret: LJRvbNDBp8aDlAqL2uwPRW9XZR1Zi7Km
    name: Hyvor Relay
    redirectURIs:
      - https://relay.pyl.one/api/oidc/callback
